In [1]:
import numpy as np
import pandas as pd

In [2]:
num_list = [1,2,3,4,5]

In [3]:
type(num_list)

list

In [4]:
arr = np.array([1,2,3,4,5,6])

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
arr = arr.reshape((2,3))

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [10]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
pd.DataFrame([1,2,3,4])

0
0  1
1  2
2  3
3  4

In [13]:
pd.DataFrame([[1,2,3], ["a", "b", "c"]])

0  1  2
0  1  2  3
1  a  b  c

In [15]:
pd.DataFrame({
    "id":[1,2,3],
    "name":["a","b","c"]
}).set_index("id")

name
id     
1     a
2     b
3     c