In [2]:
import numpy as np

In [ ]:
"""
1. Create a 3x3 matrix array with values ranging from 2 to 10.
"""

In [6]:
array_1 = np.array([[2,3,4],
                  [5,6,7],
                  [8,9,10]])

In [7]:
array_1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
"""
2. Create a numpy array having user input values and convert the integer type to the float type
of the elements of the array.
"""

In [22]:
my_array = []
a = int(input("Size of array:"))
for i in range(a):
    my_array.append(float(input("Element:")))
my_array = np.array(my_array)
print(np.floor(my_array))

Size of array:3
Element:1
Element:2
Element:3
[1. 2. 3.]


In [ ]:
"""
3. Write a Numpy program to append values to the end of an array.
"""

In [23]:
array_2 = np.array([1,5,8,7,3,4])
print("Original Array : ",array_2)

Original Array :  [1 5 8 7 3 4]


In [24]:
array_2 = np.append(array_2, [12,13,14])
print("Array after appending values at end : ",array_2)

Array after appending values at end :  [ 1  5  8  7  3  4 12 13 14]


In [ ]:
"""
4. Create two numpy arrays and add the elements of both the arrays and store the result in
sumArray.
"""

In [26]:
array_3 = np.array([45,32,15])
array_4 = np.array([50,60,17])

sumArray = array_3 + array_4
sumArray

array([95, 92, 32])

In [ ]:
"""
5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform
the following tasks:
"""

In [28]:
array1 = np.array([[10,20,30],
            [40,50,60],
            [70,80,90]])
array1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
"""
a. Extract the 1st row from the array.
"""

In [30]:
array1[:1]

array([[10, 20, 30]])

In [ ]:
"""
b. Extract the last element from the array.
"""

In [34]:
array1[2:,2:]

array([[90]])