In [ ]:
'''
1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a
Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return
[
 [5, 5, 5],
 [5, 5, 5],
 [5, 5, 5]
]
'''

In [12]:
import numpy as np

def fun(a,b,c):
    d = np.full((a,b),c)
    return d

a = int(input("Enter the first value: "))
b = int(input("Enter the second value: "))
c = int(input("Enter the third value: "))

print(fun(a,b,c))

Enter the first value: 3
Enter the second value: 3
Enter the third value: 5
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
'''
2. Create a method that takes n Numpy arrays of same dimensions, sums them and returns the
answer.
'''

In [13]:
import numpy as np

def math(a,b):
    sum1 = np.add(a,b)
    return sum1

a = np.array([10,20,30])
b = np.array([40,50,60])

math(a,b)

array([50, 70, 90])

In [ ]:
'''
3. Given a 2 D Array of n X m Dimension, Write a function that accepts this array as well as two
numbers N and M. The method should return the top-left N X M sub matrix.
'''

In [15]:
def math1(a):
    print(a[0:2, 0:2])
    
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

math1(a)

[[1 2]
 [4 5]]


In [ ]:
'''
4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two
numbers N and M The method should return the bottom-right N X M sub matrix.
'''

In [17]:
def math1(a):
    print(a[:2, :2])

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
math1(a)

[[1 2]
 [4 5]]


In [18]:
def math1(a):
    print(a[1:, 1:])
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
math1(a)        

[[5 6]
 [8 9]]


In [19]:
def func(a):
    print(a[1:, 1:])
    
d = np.arange(10,91,10).reshape(3,3)
func(d)       

[[50 60]
 [80 90]]


In [ ]:
'''
5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method
should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's
standard deviation as values
'''

In [20]:
def math2(a):
    dict1 = {"mean":np.mean(a), "std_dev":np.std(a)}
    return dict1

a = np.array([1,1,1])
math2(a)

{'mean': 1.0, 'std_dev': 0.0}